apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-python-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/josenetoo/demo-k8s-python-app-alest.git
    targetRevision: HEAD
    path: kubernetes
  destination:
    server: https://kubernetes.default.svc
    namespace: demo-python
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ApplyOutOfSyncOnly=true
